kind: pipeline
type: docker
name: build and push docker image

trigger:
  branch:
    - qee/release
  event:
    - push

clone:
  depth: 1
  retries: 3

steps:
  - name: docker buildx & push
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    privileged: true
    environment:
      REGISTRY:
        from_secret: REGISTRY
      GITEA_USERNAME:
        from_secret: GITEA_USERNAME
      GITEA_ACCESS_TOKEN:
        from_secret: GITEA_ACCESS_TOKEN
      LATEST: true
      DESCRIPTION: Releases
      VERSION: 4.6.2.10
      FULL_VERSION: release-4.6.2.10
      VUETORRENT_VERSION: 2.4.0
      CHANGELOG: https://github.com/qbittorrent/qbittorrent/compare/release-4.6.1...release-4.6.2
      UPSTREAM_IMAGE: ghcr.io/hotio/base
      UPSTREAM_TAG: alpine
      UPSTREAM_DIGEST_AMD64: sha256:f1b248466c452da319278e86d8d69f53aea51243a067678a6d3796863cbb7a5e
      UPSTREAM_DIGEST_ARM64: sha256:4d223f2c56314d3c7c50c96f0e44de8ec61f9e23250e54bd597fd0aaf0acb0ca
      TEST_URL: http://localhost:8080
    commands:
      - apk update
      - apk add skopeo
      - sleep 5
      - skopeo login -u $GITEA_USERNAME -p $GITEA_ACCESS_TOKEN $REGISTRY
      - docker login -u $GITEA_USERNAME -p $GITEA_ACCESS_TOKEN $REGISTRY
      - docker buildx create --platform linux/amd64,linux/arm64 --use
      - docker buildx build --platform linux/amd64
        --tag $REGISTRY/$GITEA_USERNAME/qbittorrent:amd64
        --file linux-amd64.Dockerfile
        --build-arg LATEST=$LATEST
        --build-arg DESCRIPTION=$DESCRIPTION
        --build-arg VERSION=$VERSION
        --build-arg FULL_VERSION=$FULL_VERSION
        --build-arg VUETORRENT_VERSION=$VUETORRENT_VERSION
        --build-arg CHANGELOG=$CHANGELOG
        --build-arg UPSTREAM_IMAGE=$UPSTREAM_IMAGE
        --build-arg UPSTREAM_TAG=$UPSTREAM_TAG
        --build-arg UPSTREAM_DIGEST_AMD64=$UPSTREAM_DIGEST_AMD64
        --build-arg TEST_URL=$TEST_URL
        --push
        .
      - docker buildx build --platform linux/arm64
        --tag $REGISTRY/$GITEA_USERNAME/qbittorrent:arm64
        --file linux-arm64.Dockerfile
        --build-arg LATEST=$LATEST
        --build-arg DESCRIPTION=$DESCRIPTION
        --build-arg VERSION=$VERSION
        --build-arg FULL_VERSION=$FULL_VERSION
        --build-arg VUETORRENT_VERSION=$VUETORRENT_VERSION
        --build-arg CHANGELOG=$CHANGELOG
        --build-arg UPSTREAM_IMAGE=$UPSTREAM_IMAGE
        --build-arg UPSTREAM_TAG=$UPSTREAM_TAG
        --build-arg UPSTREAM_DIGEST_ARM64=$UPSTREAM_DIGEST_ARM64
        --build-arg TEST_URL=$TEST_URL
        --push
        .
      - docker buildx rm --all-inactive -f
      - docker buildx imagetools create -t $REGISTRY/$GITEA_USERNAME/qbittorrent:latest
        $REGISTRY/$GITEA_USERNAME/qbittorrent:amd64
        $REGISTRY/$GITEA_USERNAME/qbittorrent:arm64
      - skopeo delete docker://$REGISTRY/$GITEA_USERNAME/qbittorrent:amd64
      - skopeo delete docker://$REGISTRY/$GITEA_USERNAME/qbittorrent:arm64

services:
  - name: docker service
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
